export { default as Login } from './Login.jsx'
export { default as Options } from './Options.jsx'
export { default as Patient } from './Patient.jsx'
export { default as Doctor } from './Doctor.jsx'
export { default as Tasks} from './Tasks.jsx'
export { default as Webcam} from './Webcam.jsx'