export { default as Login } from './Login'
export { default as Options } from './Options'
export { default as Patient } from './Patient'
export { default as Doctor } from './Doctor'
export { default as Input } from './Input'
export { default as NotFound } from './NotFound'
export { default as Profile } from './Profile'
export { default as Exercises } from './Exercises'